apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trends-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trends-engine-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60