apiVersion: v1
kind: Service
metadata:
  name: topic-repository-service
spec:
  type: ClusterIP  # Default type, makes the service only reachable within the cluste
  selector:
    app: topic-repository
  ports:
  - port: 5002 # The port the service listens on
    targetPort: 80 # The port on the pod to forward traffic to - should be equal to what define on flask