apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: topic-repository-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: topic-repository-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80