apiVersion: v1
kind: Service
metadata:
  name: trends-engine-service
spec:
  type: LoadBalancer
  selector:
    app: trends-engine
  ports:
  - port: 80 # The port the service listens on
    targetPort: 5001 # The port on the pod to forward traffic to - should be equal to what define on flask
