apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets-public-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tweets-public-api
  template:
    metadata:
      labels:
        app: tweets-public-api
    spec:
      containers:
      - name: tweets-public-api
        image: tzachioy/twitterinsightservice1-tweets-public-api-service:latest
        envFrom:
          - configMapRef:
              name: tweets-api-config
        ports:
        - containerPort: 80 # specifies which port the container within the Pod is listening on. This does not expose the port outside of the cluster or even outside of the Pod; it merely indicates to Kubernetes and to anyone reading the manifest which port the application inside the container is configured to listen on.
        resources:
          # Resource limits and requests for the container
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"